[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "eshu"
version = "0.0.1"
dependencies = [
    "Flask==3.0.3",
    "pymetasploit3==1.0.6"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]