services:

# ----- OPERATOR (CLIENT) MACHINE -----

  operator:
    build: 
      context: .
      dockerfile: operator/Dockerfile
    container_name: operator
    hostname: operator
    stdin_open: true
    tty: true
    ports:
      - "80:80"       # Auxiliary Metasploit port
      - "4444:4444"   # Reverse shell
      - "8080:8080"   # Web server port
      - "55552:55552" # RPC port
      - "55553:55553" # Additional RPC port if needed
    environment:
      - RPCPASS=memes
      - RPCPORT=1337
      - SLIVERPASS=memes
      - SLIVERPORT=1338
  #    - LPORT=4444
  #    - LHOST=0.0.0.0
  #    - DATABASE_URL=
    volumes:
      - ./operator/config_files/msfconsole.rc:/usr/src/metasploit-framework/docker/msfconsole.rc:ro
  #   - ./operator/cnc/metasploit/data:/home/msf/.msf4  # Persistent storage for Metasploit    
    networks:
      localnet:
        ipv4_address: 10.1.1.2

# ----- ESHU CLP API -----

#  eshuapi: 
#    build: .
#    container_name: eshu
#    hostname: eshu
#    ports:
#      - "5000:5000" # Default port for Flask
#    env_file: # Can list mutliple envs
#      - ./config_files/msf_config.env
#    environment:
#      - ESHU_PORT=5000
#    stdin_open: true
#    tty: true
#    networks:
#      localnet:
#        ipv4_address: 10.1.1.99
#    # volumes: # Or other volumes you want to use.
#    #   - ./states:/states

  # ----- VICTIM MACHINES -----

  # Metasploitable2 Victim Machine
  metasploitable2:
    build:
      context: .
      dockerfile: operator/Dockerfile
    image: tleemcjr/metasploitable2
    container_name: metasploitable2
    hostname: metasploitable2
    entrypoint: bash -c '/bin/services.sh && tail -f /dev/null'
    command: sleep infinite
    networks:
      localnet:
        ipv4_address: 10.1.1.3

  # Sliver Machine
  sliver:
    build: 
      context: .
      dockerfile: sliver/Dockerfile  # Path to your Dockerfile
    container_name: sliver-server
    ports:
      - "8888:8888"   # Map host port 8888 to container port 8888 (for Sliver server UI/API)
      - "31337:31337" # Map host port 31337 to container port 31337 (for Sliver implants)
    volumes:
      - ./operator/config_files:/opt/sliver/config_files # If you have external configs
      - ./data:/opt/sliver/data  # Persist Sliver's generated implants or other data
    networks:
      - sliver-network
    environment:
      - GOPATH=/root/go
      - PATH=/opt/sliver/bin:$GOPATH/bin:/usr/local/go/bin:$PATH
    restart: unless-stopped  # Automatically restart if it crashes
    

# ----- NETWORK -----

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.1
  
  sliver-network:
    driver: bridge
