services:

  # Attacker Machine
  operator:
    build: ./operator
    container_name: operator
    volumes:
      - ./operator/cnc/metasploit/data:/home/msf/.msf4  # Persistent storage for Metasploit
    # - ./operator/api:/opt/api-data
    ports:
      - "4444:4444"   # Reverse shell
      - "5000:5000"
      - "8080:8080"   # Web server port
      - "8888:8888"
      - "1337:1337"
    hostname: operator
    tty: true
    stdin_open: true
    networks:
      localnet:
        ipv4_address: 10.1.1.2

  # Metasploitable2 Victim Machine
  metasploitable2:
    build: ./metasploitable2
    container_name: metasploitable2
    volumes:
      - ./metasploitable2/data:/var/data
    ports:
      - "21:21"    # FTP
      - "22:22"    # SSH
      - "80:80"    # HTTP
      - "3307:3306"  # MySQL
    hostname: metasploitable2
    networks:
      localnet:
        ipv4_address: 10.1.1.3

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.1